curl -d "props={\"description\":\"Generated by JEST tests. Customer 1676290904050\",\"email\":\"1676290904050@yopmail.com\",\"metadata\":{\"testField\":\"testValue1\",\"testField2\":\"testValue2\"},\"name\":\"Customer 1676290904050\",\"phone\":\"+1 555 555 5555\",\"address\":{\"city\":\"San Francisco\",\"country\":\"US\",\"line1\":\"1234 Main Street\",\"line2\":\"Apt. 4\",\"postal_code\":\"94111\",\"state\":\"CA\"}}
" -X POST http://localhost:3000/generate-customer

curl -d "props={\"email\":\"1676290904742@yopmail.com\"}" -X POST http://localhost:3000/generate-account

curl -d "props={\"customerId\":\"cus_NLiTz4ISXMYeno\",\"payInAmount\":1000,\"currency\":\"usd\"}" -X POST http://localhost:3000/payment-sheet-handler
