import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View, Button } from 'react-native';

import generateCustomer from './functions/generate-customer';

export default function App() {
	const generateCustomer_ = async () => {
		generateCustomer({
			"description": "Generated by JEST tests. Customer 1676290904050",
			"email": "1676290904050@yopmail.com",
			"metadata": {
				"testField": "testValue1",
				"testField2": "testValue2"
			},
			"name": "Customer 1676290904050",
			"phone": "+1 555 555 5555",
			"address": {
				"city": "San Francisco",
				"country": "US",
				"line1": "1234 Main Street",
				"line2": "Apt. 4",
				"postal_code": "94111",
				"state": "CA"
			}
		});
	};

	return (
		<View style={styles.container}>
			<Text>Open up App.js to start working on your app!</Text>
			<StatusBar style="auto" />
			<Button
				title="Generate Customer"
				onPress={generateCustomer_}
			/>
			<Text> </Text>
		</View>
	);
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#fff',
		alignItems: 'center',
		justifyContent: 'center',
	},
});
